spring:
  application:
    name: game-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/gamedb
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true